/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-01-13 17:02:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.modules.heartbeat;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class heartbeat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005finsertTemplate_0026_005ftemplate;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ft_005fputAttribute_0026_005fvalue_005fname_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ft_005finsertTemplate_0026_005ftemplate = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ft_005fputAttribute_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ft_005finsertTemplate_0026_005ftemplate.release();
    _005fjspx_005ftagPool_005ft_005fputAttribute_0026_005fvalue_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_t_005finsertTemplate_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005finsertTemplate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:insertTemplate
    org.apache.tiles.jsp.taglib.InsertTemplateTag _jspx_th_t_005finsertTemplate_005f0 = (org.apache.tiles.jsp.taglib.InsertTemplateTag) _005fjspx_005ftagPool_005ft_005finsertTemplate_0026_005ftemplate.get(org.apache.tiles.jsp.taglib.InsertTemplateTag.class);
    _jspx_th_t_005finsertTemplate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005finsertTemplate_005f0.setParent(null);
    // /WEB-INF/jsp/modules/heartbeat/heartbeat.jsp(24,0) name = template type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005finsertTemplate_005f0.setTemplate("/WEB-INF/jsp/templates/heartbeatOptin.jsp");
    int[] _jspx_push_body_count_t_005finsertTemplate_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_t_005finsertTemplate_005f0 = _jspx_th_t_005finsertTemplate_005f0.doStartTag();
      if (_jspx_eval_t_005finsertTemplate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_t_005finsertTemplate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_push_body_count_t_005finsertTemplate_005f0[0]++;
          _jspx_th_t_005finsertTemplate_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_t_005finsertTemplate_005f0.doInitBody();
        }
        do {
          out.write("\r\n");
          out.write("    ");
          if (_jspx_meth_t_005fputAttribute_005f0(_jspx_th_t_005finsertTemplate_005f0, _jspx_page_context, _jspx_push_body_count_t_005finsertTemplate_005f0))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_t_005finsertTemplate_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_t_005finsertTemplate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
          _jspx_push_body_count_t_005finsertTemplate_005f0[0]--;
        }
      }
      if (_jspx_th_t_005finsertTemplate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_t_005finsertTemplate_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_t_005finsertTemplate_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_t_005finsertTemplate_005f0.doFinally();
      _005fjspx_005ftagPool_005ft_005finsertTemplate_0026_005ftemplate.reuse(_jspx_th_t_005finsertTemplate_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_t_005fputAttribute_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_t_005finsertTemplate_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_t_005finsertTemplate_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:putAttribute
    org.apache.tiles.jsp.taglib.PutAttributeTag _jspx_th_t_005fputAttribute_005f0 = (org.apache.tiles.jsp.taglib.PutAttributeTag) _005fjspx_005ftagPool_005ft_005fputAttribute_0026_005fvalue_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.PutAttributeTag.class);
    _jspx_th_t_005fputAttribute_005f0.setPageContext(_jspx_page_context);
    _jspx_th_t_005fputAttribute_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_t_005finsertTemplate_005f0);
    // /WEB-INF/jsp/modules/heartbeat/heartbeat.jsp(25,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fputAttribute_005f0.setName("containerClass");
    // /WEB-INF/jsp/modules/heartbeat/heartbeat.jsp(25,4) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_t_005fputAttribute_005f0.setValue("hidden");
    int[] _jspx_push_body_count_t_005fputAttribute_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_t_005fputAttribute_005f0 = _jspx_th_t_005fputAttribute_005f0.doStartTag();
      if (_jspx_th_t_005fputAttribute_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_t_005fputAttribute_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_t_005fputAttribute_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_t_005fputAttribute_005f0.doFinally();
      _005fjspx_005ftagPool_005ft_005fputAttribute_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_t_005fputAttribute_005f0);
    }
    return false;
  }
}
