/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-01-13 17:02:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.modules.about;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.jaspersoft.ji.license.LicenseManager;
import com.jaspersoft.ji.license.LicenseCheckStatus;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/spring.tld", Long.valueOf(1418898135000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005finsertTemplate_0026_005ftemplate;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fputAttribute_0026_005fvalue_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftiles_005fputAttribute_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftiles_005finsertTemplate_0026_005ftemplate = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fputAttribute_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftiles_005fputAttribute_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftiles_005finsertTemplate_0026_005ftemplate.release();
    _005fjspx_005ftagPool_005ftiles_005fputAttribute_0026_005fvalue_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005ftiles_005fputAttribute_0026_005fname.release();
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      //  tiles:insertTemplate
      org.apache.tiles.jsp.taglib.InsertTemplateTag _jspx_th_tiles_005finsertTemplate_005f0 = (org.apache.tiles.jsp.taglib.InsertTemplateTag) _005fjspx_005ftagPool_005ftiles_005finsertTemplate_0026_005ftemplate.get(org.apache.tiles.jsp.taglib.InsertTemplateTag.class);
      _jspx_th_tiles_005finsertTemplate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tiles_005finsertTemplate_005f0.setParent(null);
      // /WEB-INF/jsp/modules/about/about.jsp(13,0) name = template type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertTemplate_005f0.setTemplate("/WEB-INF/jsp/templates/aboutBox.jsp");
      int[] _jspx_push_body_count_tiles_005finsertTemplate_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_tiles_005finsertTemplate_005f0 = _jspx_th_tiles_005finsertTemplate_005f0.doStartTag();
        if (_jspx_eval_tiles_005finsertTemplate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_tiles_005finsertTemplate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.pushBody();
            _jspx_push_body_count_tiles_005finsertTemplate_005f0[0]++;
            _jspx_th_tiles_005finsertTemplate_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
            _jspx_th_tiles_005finsertTemplate_005f0.doInitBody();
          }
          do {
            out.write("\r\n");
            out.write("    ");
            if (_jspx_meth_tiles_005fputAttribute_005f0(_jspx_th_tiles_005finsertTemplate_005f0, _jspx_page_context, _jspx_push_body_count_tiles_005finsertTemplate_005f0))
              return;
            out.write("\r\n");
            out.write("    ");
            //  tiles:putAttribute
            org.apache.tiles.jsp.taglib.PutAttributeTag _jspx_th_tiles_005fputAttribute_005f1 = (org.apache.tiles.jsp.taglib.PutAttributeTag) _005fjspx_005ftagPool_005ftiles_005fputAttribute_0026_005fname.get(org.apache.tiles.jsp.taglib.PutAttributeTag.class);
            _jspx_th_tiles_005fputAttribute_005f1.setPageContext(_jspx_page_context);
            _jspx_th_tiles_005fputAttribute_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsertTemplate_005f0);
            // /WEB-INF/jsp/modules/about/about.jsp(15,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_tiles_005fputAttribute_005f1.setName("bodyContent");
            int[] _jspx_push_body_count_tiles_005fputAttribute_005f1 = new int[] { 0 };
            try {
              int _jspx_eval_tiles_005fputAttribute_005f1 = _jspx_th_tiles_005fputAttribute_005f1.doStartTag();
              if (_jspx_eval_tiles_005fputAttribute_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                if (_jspx_eval_tiles_005fputAttribute_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.pushBody();
                  _jspx_push_body_count_tiles_005fputAttribute_005f1[0]++;
                  _jspx_th_tiles_005fputAttribute_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
                  _jspx_th_tiles_005fputAttribute_005f1.doInitBody();
                }
                do {
                  out.write("\r\n");
                  out.write("        ");

            LicenseManager licenseManager = LicenseManager.getInstance();
            LicenseCheckStatus licenseCheckStatus = licenseManager.checkLicense();

            if (!licenseCheckStatus.isLicenseAccepted()) { 
                  out.write("\r\n");
                  out.write("        <p class=\"message\">");
                  out.print(licenseCheckStatus.getMessage());
                  out.write("</p>\r\n");
                  out.write("        ");
  } else { 
                  out.write("\r\n");
                  out.write("            <p class=\"message\">");
                  if (_jspx_meth_spring_005fmessage_005f0(_jspx_th_tiles_005fputAttribute_005f1, _jspx_page_context, _jspx_push_body_count_tiles_005fputAttribute_005f1))
                    return;
                  out.write(":&nbsp;<span class=\"emphasis\">");
                  out.print( licenseManager.getProductEditionName() );
                  out.write("</span></p>\r\n");
                  out.write("            ");
  String supportedFeatureNames = licenseManager.getSupportedFeatureNames();
                if (supportedFeatureNames != null) {    
                  out.write("\r\n");
                  out.write("            <p class=\"message\">");
                  if (_jspx_meth_spring_005fmessage_005f1(_jspx_th_tiles_005fputAttribute_005f1, _jspx_page_context, _jspx_push_body_count_tiles_005fputAttribute_005f1))
                    return;
                  out.write(": <span class=\"emphasis\">");
                  out.print(supportedFeatureNames);
                  out.write("</span></p>\r\n");
                  out.write("            ");
  }   
                  out.write("\r\n");
                  out.write("            <p class=\"message\">");
                  if (_jspx_meth_spring_005fmessage_005f2(_jspx_th_tiles_005fputAttribute_005f1, _jspx_page_context, _jspx_push_body_count_tiles_005fputAttribute_005f1))
                    return;
                  out.write(": <span class=\"emphasis\">");
                  if (_jspx_meth_spring_005fmessage_005f3(_jspx_th_tiles_005fputAttribute_005f1, _jspx_page_context, _jspx_push_body_count_tiles_005fputAttribute_005f1))
                    return;
                  out.write("</span></p>\r\n");
                  out.write("            <p class=\"message\">");
                  if (_jspx_meth_spring_005fmessage_005f4(_jspx_th_tiles_005fputAttribute_005f1, _jspx_page_context, _jspx_push_body_count_tiles_005fputAttribute_005f1))
                    return;
                  out.write(": <span class=\"emphasis\">");
                  if (_jspx_meth_spring_005fmessage_005f5(_jspx_th_tiles_005fputAttribute_005f1, _jspx_page_context, _jspx_push_body_count_tiles_005fputAttribute_005f1))
                    return;
                  out.write('_');
                  if (_jspx_meth_spring_005fmessage_005f6(_jspx_th_tiles_005fputAttribute_005f1, _jspx_page_context, _jspx_push_body_count_tiles_005fputAttribute_005f1))
                    return;
                  out.write("</span></p>\r\n");
                  out.write("            ");

                String licenseType;
                if (licenseManager.isDevelopmentEnvironmentType()) {
                    licenseType = LicenseManager.ENV_TYPE_DEVELOPMENT;
                } else {
                    licenseType = licenseManager.getLicenseTypeString();
                }
            
                  out.write("\r\n");
                  out.write("            <p class=\"message\">");
                  if (_jspx_meth_spring_005fmessage_005f7(_jspx_th_tiles_005fputAttribute_005f1, _jspx_page_context, _jspx_push_body_count_tiles_005fputAttribute_005f1))
                    return;
                  out.write(": <span class=\"emphasis\">");
                  out.print(licenseType);
                  out.write("</span></p>\r\n");
                  out.write("            <p class=\"message\">");
                  if (_jspx_meth_spring_005fmessage_005f8(_jspx_th_tiles_005fputAttribute_005f1, _jspx_page_context, _jspx_push_body_count_tiles_005fputAttribute_005f1))
                    return;
                  out.write(": <span class=\"emphasis\">");
                  out.print(licenseManager.getFormattedExpirationDate());
                  out.write("</span></p>\r\n");
                  out.write("        ");
  } 
                  out.write("\r\n");
                  out.write("\r\n");
                  out.write("    ");
                  int evalDoAfterBody = _jspx_th_tiles_005fputAttribute_005f1.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
                if (_jspx_eval_tiles_005fputAttribute_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
                  out = _jspx_page_context.popBody();
                  _jspx_push_body_count_tiles_005fputAttribute_005f1[0]--;
                }
              }
              if (_jspx_th_tiles_005fputAttribute_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
            } catch (java.lang.Throwable _jspx_exception) {
              while (_jspx_push_body_count_tiles_005fputAttribute_005f1[0]-- > 0)
                out = _jspx_page_context.popBody();
              _jspx_th_tiles_005fputAttribute_005f1.doCatch(_jspx_exception);
            } finally {
              _jspx_th_tiles_005fputAttribute_005f1.doFinally();
              _005fjspx_005ftagPool_005ftiles_005fputAttribute_0026_005fname.reuse(_jspx_th_tiles_005fputAttribute_005f1);
            }
            out.write('\r');
            out.write('\n');
            int evalDoAfterBody = _jspx_th_tiles_005finsertTemplate_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_tiles_005finsertTemplate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
            _jspx_push_body_count_tiles_005finsertTemplate_005f0[0]--;
          }
        }
        if (_jspx_th_tiles_005finsertTemplate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_tiles_005finsertTemplate_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_tiles_005finsertTemplate_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_tiles_005finsertTemplate_005f0.doFinally();
        _005fjspx_005ftagPool_005ftiles_005finsertTemplate_0026_005ftemplate.reuse(_jspx_th_tiles_005finsertTemplate_005f0);
      }
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tiles_005fputAttribute_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005finsertTemplate_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tiles_005finsertTemplate_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:putAttribute
    org.apache.tiles.jsp.taglib.PutAttributeTag _jspx_th_tiles_005fputAttribute_005f0 = (org.apache.tiles.jsp.taglib.PutAttributeTag) _005fjspx_005ftagPool_005ftiles_005fputAttribute_0026_005fvalue_005fname_005fnobody.get(org.apache.tiles.jsp.taglib.PutAttributeTag.class);
    _jspx_th_tiles_005fputAttribute_005f0.setPageContext(_jspx_page_context);
    _jspx_th_tiles_005fputAttribute_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005finsertTemplate_005f0);
    // /WEB-INF/jsp/modules/about/about.jsp(14,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fputAttribute_005f0.setName("containerClass");
    // /WEB-INF/jsp/modules/about/about.jsp(14,4) name = value type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_tiles_005fputAttribute_005f0.setValue("hidden centered_vert centered_horz");
    int[] _jspx_push_body_count_tiles_005fputAttribute_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_tiles_005fputAttribute_005f0 = _jspx_th_tiles_005fputAttribute_005f0.doStartTag();
      if (_jspx_th_tiles_005fputAttribute_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_tiles_005fputAttribute_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_tiles_005fputAttribute_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_tiles_005fputAttribute_005f0.doFinally();
      _005fjspx_005ftagPool_005ftiles_005fputAttribute_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_tiles_005fputAttribute_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005fputAttribute_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tiles_005fputAttribute_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005fputAttribute_005f1);
    // /WEB-INF/jsp/modules/about/about.jsp(23,31) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f0.setCode("NAV_146_ABOUT_LICENSE_PRODUCT_EDITION");
    int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
      if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005fputAttribute_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tiles_005fputAttribute_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005fputAttribute_005f1);
    // /WEB-INF/jsp/modules/about/about.jsp(26,31) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f1.setCode("NAV_147_ABOUT_LICENSE_FEATURES");
    int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
      if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f1.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005fputAttribute_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tiles_005fputAttribute_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f2 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005fputAttribute_005f1);
    // /WEB-INF/jsp/modules/about/about.jsp(28,31) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f2.setCode("dialog.aboutBox.productVersion");
    int[] _jspx_push_body_count_spring_005fmessage_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f2 = _jspx_th_spring_005fmessage_005f2.doStartTag();
      if (_jspx_th_spring_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f2.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005fputAttribute_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tiles_005fputAttribute_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f3 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005fputAttribute_005f1);
    // /WEB-INF/jsp/modules/about/about.jsp(28,111) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f3.setCode("PRO_VERSION");
    int[] _jspx_push_body_count_spring_005fmessage_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f3 = _jspx_th_spring_005fmessage_005f3.doStartTag();
      if (_jspx_th_spring_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f3.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005fputAttribute_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tiles_005fputAttribute_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f4 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005fputAttribute_005f1);
    // /WEB-INF/jsp/modules/about/about.jsp(29,31) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f4.setCode("dialog.aboutBox.build");
    int[] _jspx_push_body_count_spring_005fmessage_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f4 = _jspx_th_spring_005fmessage_005f4.doStartTag();
      if (_jspx_th_spring_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f4.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005fputAttribute_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tiles_005fputAttribute_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f5 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005fputAttribute_005f1);
    // /WEB-INF/jsp/modules/about/about.jsp(29,102) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f5.setCode("BUILD_DATE_STAMP");
    int[] _jspx_push_body_count_spring_005fmessage_005f5 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f5 = _jspx_th_spring_005fmessage_005f5.doStartTag();
      if (_jspx_th_spring_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f5[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f5.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f5.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005fputAttribute_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tiles_005fputAttribute_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f6 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f6.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005fputAttribute_005f1);
    // /WEB-INF/jsp/modules/about/about.jsp(29,144) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f6.setCode("BUILD_TIME_STAMP");
    int[] _jspx_push_body_count_spring_005fmessage_005f6 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f6 = _jspx_th_spring_005fmessage_005f6.doStartTag();
      if (_jspx_th_spring_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f6[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f6.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f6.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005fputAttribute_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tiles_005fputAttribute_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f7 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f7.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005fputAttribute_005f1);
    // /WEB-INF/jsp/modules/about/about.jsp(38,31) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f7.setCode("NAV_142_ABOUT_LICENSE_TYPE");
    int[] _jspx_push_body_count_spring_005fmessage_005f7 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f7 = _jspx_th_spring_005fmessage_005f7.doStartTag();
      if (_jspx_th_spring_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f7[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f7.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f7.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f7);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_tiles_005fputAttribute_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_tiles_005fputAttribute_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f8 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f8.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tiles_005fputAttribute_005f1);
    // /WEB-INF/jsp/modules/about/about.jsp(39,31) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f8.setCode("NAV_143_ABOUT_LICENSE_EXPIRATION");
    int[] _jspx_push_body_count_spring_005fmessage_005f8 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f8 = _jspx_th_spring_005fmessage_005f8.doStartTag();
      if (_jspx_th_spring_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f8[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f8.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f8.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f8);
    }
    return false;
  }
}
